local palette = require("earthshine.colors").pallete
local preset = require("earthshine.colors").preset
local debug = require("earthshine.colors").debug
local code = require("earthshine.colors").code

local M = {}

M.get = function()
	return {
		ColorColumn = debug,
		Conceal = { bg = "NONE" },
		CurSearch = { fg = preset.bg, bg = preset.attention },
		-- Cursor = { fg = palette.text, bg = palette.blue },
		CursorColumn = { bg = preset.muted },
		-- -- CursorIM = {},
		CursorLine = { bg = preset.float },
		CursorLineNr = { fg = preset.attention },
		-- -- DarkenedPanel = { },
		-- -- DarkenedStatusline = {},
		Added = { fg = preset.git_add },
		Removed = { fg = preset.git_delete },
		Changed = { fg = preset.git_change },
		DiffAdd = { link = "Added" },
		DiffChange = { link = "Changed" },
		DiffDelete = { link = "Removed" },
		DiffText = { bg = preset.git_text },
		diffAdded = { link = "DiffAdd" },
		diffChanged = { link = "DiffChange" },
		diffRemoved = { link = "DiffDelete" },
		Directory = { fg = palette.blue },
		ErrorMsg = { fg = preset.error, bold = true },
		FloatTitle = { fg = preset.attention },
		FoldColumn = { fg = preset.muted },
		Folded = { fg = preset.bg, bg = preset.muted },
		IncSearch = { link = "CurSearch" },
		LineNr = { fg = preset.muted },
		MatchParen = { fg = preset.attention },
		ModeMsg = { fg = preset.error },
		MoreMsg = { fg = preset.text },
		NonText = { fg = preset.muted },
		Normal = { fg = preset.text, bg = preset.bg },
		NormalFloat = { fg = preset.text, bg = preset.float },
		NormalNC = { bg = preset.float },
		NvimInternalError = { link = "ErrorMsg" },
		Pmenu = { bg = preset.float, fg = preset.text },
		PmenuSbar = { bg = preset.float },
		PmenuSel = { bg = preset.attention, fg = preset.bg },
		PmenuThumb = { bg = preset.muted },
		Search = { bg = preset.attention, fg = preset.bg },
		SignColumn = { bg = "NONE", fg = preset.muted },
		SpecialKey = { fg = preset.attention, bg = "NONE" },
		SpellBad = { undercurl = true, sp = preset.muted },
		SpellCap = { undercurl = true, sp = preset.muted },
		SpellLocal = { undercurl = true, sp = preset.muted },
		SpellRare = { undercurl = true, sp = preset.muted },
		StatusLine = { bg = preset.float },
		StatusLineNC = { bg = preset.muted },
		StatusLineTerm = { bg = preset.float },
		StatusLineTermNC = { bg = preset.muted },
		Substitute = { link = "IncSearch" },
		TabLine = { bg = preset.bg },
		TabLineFill = { bg = preset.float },
		TabLineSel = { bg = preset.attention, fg = palette.black },
		Title = { fg = preset.attention },
		VertSplit = { fg = preset.muted },
		Visual = { bg = preset.mode_visual },
		-- -- VisualNOS = {},
		WarningMsg = { fg = preset.warning },
		-- -- Whitespace = {},
		WildMenu = { link = "IncSearch" },
		WinSeparator = { bg = preset.muted },

		DiagnosticError = { fg = preset.error },
		DiagnosticHint = { fg = preset.info },
		DiagnosticInfo = { fg = preset.info },
		DiagnosticOk = { fg = preset.success },
		DiagnosticWarn = { fg = preset.warning },
		DiagnosticDefaultError = { link = "DiagnosticError" },
		DiagnosticDefaultHint = { link = "DiagnosticHint" },
		DiagnosticDefaultInfo = { link = "DiagnosticInfo" },
		DiagnosticDefaultOk = { link = "DiagnosticOk" },
		DiagnosticDefaultWarn = { link = "DiagnosticWarn" },
		DiagnosticFloatingError = { link = "DiagnosticError" },
		DiagnosticFloatingHint = { link = "DiagnosticHint" },
		DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
		DiagnosticFloatingOk = { link = "DiagnosticOk" },
		DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
		DiagnosticSignError = { link = "DiagnosticError" },
		DiagnosticSignHint = { link = "DiagnosticHint" },
		DiagnosticSignInfo = { link = "DiagnosticInfo" },
		DiagnosticSignOk = { link = "DiagnosticOk" },
		DiagnosticSignWarn = { link = "DiagnosticWarn" },
		DiagnosticUnderlineError = { sp = preset.error, undercurl = true },
		DiagnosticUnderlineHint = { sp = preset.info, undercurl = true },
		DiagnosticUnderlineInfo = { sp = preset.info, undercurl = true },
		DiagnosticUnderlineOk = { sp = preset.success, undercurl = true },
		DiagnosticUnderlineWarn = { sp = preset.warning, undercurl = true },
		DiagnosticVirtualTextError = { fg = preset.error },
		DiagnosticVirtualTextHint = { fg = preset.info },
		DiagnosticVirtualTextInfo = { fg = preset.info },
		DiagnosticVirtualTextOk = { fg = preset.success },
		DiagnosticVirtualTextWarn = { fg = preset.warning },

		Boolean = code.boolean,
		Character = code.string,
		Comment = code.comment,
		Conditional = code.keyword,
		Constant = code.comment,
		-- Debug = { fg = palette.rose },
		Define = debug,
		-- Delimiter = { fg = palette.subtle },
		Error = { fg = preset.error },
		-- Exception = { fg = palette.pine },
		Float = { link = "Number" },
		Function = code.func,
		-- Identifier = { fg = palette.text },
		-- Include = { fg = palette.pine },
		Keyword = code.keyword,
		-- Label = { fg = palette.foam },
		-- LspCodeLens = { fg = palette.subtle },
		-- LspCodeLensSeparator = { fg = palette.muted },
		-- LspInlayHint = { fg = palette.muted, bg = palette.muted, blend = 10 },
		-- LspReferenceRead = { bg = palette.highlight_med },
		-- LspReferenceText = { bg = palette.highlight_med },
		-- LspReferenceWrite = { bg = palette.highlight_med },
		-- Macro = { fg = palette.iris },
		Number = code.number,
		Operator = code.operator,
		-- PreCondit = { fg = palette.iris },
		-- PreProc = { link = "PreCondit" },
		-- Repeat = { fg = palette.pine },
		Special = code.operator,
		-- SpecialChar = { link = "Special" },
		-- SpecialComment = { fg = palette.iris },
		-- Statement = { fg = palette.pine, bold = styles.bold },
		-- StorageClass = { fg = palette.foam },
		String = code.string,
		-- Structure = { fg = palette.foam },
		-- Tag = { fg = palette.foam },
		-- Todo = { fg = palette.rose, bg = palette.rose, blend = 20 },
		Type = code.type,
		-- TypeDef = { link = "Type" },
		-- Underlined = { fg = palette.iris, underline = true },
		--
		-- healthError = { fg = groups.error },
		-- healthSuccess = { fg = groups.info },
		-- healthWarning = { fg = groups.warn },
		--
		-- htmlArg = { fg = palette.iris },
		-- htmlBold = { bold = styles.bold },
		-- htmlEndTag = { fg = palette.subtle },
		-- htmlH1 = { link = "markdownH1" },
		-- htmlH2 = { link = "markdownH2" },
		-- htmlH3 = { link = "markdownH3" },
		-- htmlH4 = { link = "markdownH4" },
		-- htmlH5 = { link = "markdownH5" },
		-- htmlItalic = { italic = styles.italic },
		-- htmlLink = { link = "markdownUrl" },
		-- htmlTag = { fg = palette.subtle },
		-- htmlTagN = { fg = palette.text },
		-- htmlTagName = { fg = palette.foam },
		--
		-- markdownDelimiter = { fg = palette.subtle },
		-- markdownH1 = { fg = groups.h1, bold = styles.bold },
		-- markdownH1Delimiter = { link = "markdownH1" },
		-- markdownH2 = { fg = groups.h2, bold = styles.bold },
		-- markdownH2Delimiter = { link = "markdownH2" },
		-- markdownH3 = { fg = groups.h3, bold = styles.bold },
		-- markdownH3Delimiter = { link = "markdownH3" },
		-- markdownH4 = { fg = groups.h4, bold = styles.bold },
		-- markdownH4Delimiter = { link = "markdownH4" },
		-- markdownH5 = { fg = groups.h5, bold = styles.bold },
		-- markdownH5Delimiter = { link = "markdownH5" },
		-- markdownH6 = { fg = groups.h6, bold = styles.bold },
		-- markdownH6Delimiter = { link = "markdownH6" },
		-- markdownLinkText = { link = "markdownUrl" },
		-- markdownUrl = { fg = groups.link, sp = groups.link, underline = true },
		--
		-- mkdCode = { fg = palette.foam, italic = styles.italic },
		-- mkdCodeDelimiter = { fg = palette.rose },
		-- mkdCodeEnd = { fg = palette.foam },
		-- mkdCodeStart = { fg = palette.foam },
		-- mkdFootnotes = { fg = palette.foam },
		-- mkdID = { fg = palette.foam, underline = true },
		-- mkdInlineURL = { link = "markdownUrl" },
		-- mkdLink = { link = "markdownUrl" },
		-- mkdLinkDef = { link = "markdownUrl" },
		-- mkdListItemLine = { fg = palette.text },
		-- mkdRule = { fg = palette.subtle },
		-- mkdURL = { link = "markdownUrl" },
		--
		-- --- Treesitter
		-- --- |:help treesitter-highlight-groups|
		["@variable"] = code.variable,
		["@variable.builtin"] = code.builtin,
		["@variable.parameter"] = code.param,
		["@variable.member"] = { link = "@property" },
		["@variable.parameter.builtin"] = { link = "@variable.builtin" },
		-- ["@variable.member"] = { fg = palette.foam },
		--
		["@constant"] = code.constant,
		["@constant.builtin"] = { link = "@variable.builtin" },
		-- ["@constant.macro"] = { fg = palette.gold },
		--
		["@module"] = code.module,
		["@module.builtin"] = { link = "@variable.builtin" },
		-- ["@label"] = { link = "Label" },
		--
		["@string"] = { link = "String" },
		-- -- ["@string.documentation"] = {},
		["@string.regexp"] = { fg = preset.attention },
		["@string.escape"] = { fg = preset.attention },
		["@string.special"] = { link = "Special" },
		["@string.special.symbol"] = { link = "Identifier" },
		-- ["@string.special.url"] = { fg = groups.link },
		-- -- ["@string.special.path"] = {},

		["@character"] = { link = "Character" },
		["@character.special"] = { link = "Character" },
		--
		["@boolean"] = { link = "Boolean" },
		["@number"] = { link = "Number" },
		["@number.float"] = { link = "Number" },
		["@float"] = { link = "Number" },
		--
		["@type"] = { link = "Type" },
		["@type.builtin"] = { link = "@type" },
		--
		-- ["@attribute"] = { fg = palette.iris },
		["@attribute.builtin"] = { link = "@variable.builtin" },
		["@property"] = code.property,
		["@parameter"] = code.param,
		["@function"] = code.func,
		["@function.builtin"] = { link = "@function" },
		-- -- ["@function.call"] = {},
		["@function.macro"] = { link = "Function" },
		--

		--
		-- ["@constructor"] = { fg = palette.foam },
		["@operator"] = { link = "Operator" },
		--
		["@keyword"] = { link = "Keyword" },
		-- -- ["@keyword.coroutine"] = {},
		-- -- ["@keyword.function"] = {},
		-- ["@keyword.operator"] = { fg = palette.subtle },
		-- ["@keyword.import"] = { fg = palette.pine },
		-- ["@keyword.storage"] = { fg = palette.foam },
		-- ["@keyword.repeat"] = { fg = palette.pine },
		-- ["@keyword.return"] = { fg = palette.pine },
		-- ["@keyword.debug"] = { fg = palette.rose },
		-- ["@keyword.exception"] = { fg = palette.pine },
		--
		-- ["@keyword.conditional"] = { fg = palette.pine },
		-- ["@keyword.conditional.ternary"] = { fg = palette.pine },
		--
		-- ["@keyword.directive"] = { fg = palette.iris },
		-- ["@keyword.directive.define"] = { fg = palette.iris },
		--
		-- --- Punctuation
		-- ["@punctuation.delimiter"] = { fg = palette.subtle },
		-- ["@punctuation.bracket"] = { fg = palette.subtle },
		["@punctuation.special"] = { link = "Special" },

		-- --- Comments
		["@comment"] = { link = "Comment" },
		-- -- ["@comment.documentation"] = {},
		--
		-- ["@comment.error"] = { fg = groups.error },
		-- ["@comment.warning"] = { fg = groups.warn },
		-- ["@comment.todo"] = { fg = groups.todo, bg = groups.todo, blend = 15 },
		-- ["@comment.hint"] = { fg = groups.hint, bg = groups.hint, blend = 15 },
		-- ["@comment.info"] = { fg = groups.info, bg = groups.info, blend = 15 },
		-- ["@comment.note"] = { fg = groups.note, bg = groups.note, blend = 15 },
		--
		-- --- Markup
		-- ["@markup.strong"] = { bold = styles.bold },
		-- ["@markup.italic"] = { italic = styles.italic },
		-- ["@markup.strikethrough"] = { strikethrough = true },
		-- ["@markup.underline"] = { underline = true },
		--
		-- ["@markup.heading"] = { fg = palette.foam, bold = styles.bold },
		--
		-- ["@markup.quote"] = { fg = palette.text },
		-- ["@markup.math"] = { link = "Special" },
		-- ["@markup.environment"] = { link = "Macro" },
		-- ["@markup.environment.name"] = { link = "@type" },
		--
		-- -- ["@markup.link"] = {},
		-- ["@markup.link.markdown_inline"] = { fg = palette.subtle },
		-- ["@markup.link.label.markdown_inline"] = { fg = palette.foam },
		-- ["@markup.link.url"] = { fg = groups.link },
		--
		-- -- ["@markup.raw"] = { bg = palette.surface },
		-- -- ["@markup.raw.block"] = { bg = palette.surface },
		-- ["@markup.raw.delimiter.markdown"] = { fg = palette.subtle },
		--
		-- ["@markup.list"] = { fg = palette.pine },
		-- ["@markup.list.checked"] = { fg = palette.foam, bg = palette.foam, blend = 10 },
		-- ["@markup.list.unchecked"] = { fg = palette.text },
		--
		-- -- Markdown headings
		-- ["@markup.heading.1.markdown"] = { link = "markdownH1" },
		-- ["@markup.heading.2.markdown"] = { link = "markdownH2" },
		-- ["@markup.heading.3.markdown"] = { link = "markdownH3" },
		-- ["@markup.heading.4.markdown"] = { link = "markdownH4" },
		-- ["@markup.heading.5.markdown"] = { link = "markdownH5" },
		-- ["@markup.heading.6.markdown"] = { link = "markdownH6" },
		-- ["@markup.heading.1.marker.markdown"] = { link = "markdownH1Delimiter" },
		-- ["@markup.heading.2.marker.markdown"] = { link = "markdownH2Delimiter" },
		-- ["@markup.heading.3.marker.markdown"] = { link = "markdownH3Delimiter" },
		-- ["@markup.heading.4.marker.markdown"] = { link = "markdownH4Delimiter" },
		-- ["@markup.heading.5.marker.markdown"] = { link = "markdownH5Delimiter" },
		-- ["@markup.heading.6.marker.markdown"] = { link = "markdownH6Delimiter" },
		--
		-- ["@diff.plus"] = { fg = groups.git_add, bg = groups.git_add, blend = 20 },
		-- ["@diff.minus"] = { fg = groups.git_delete, bg = groups.git_delete, blend = 20 },
		-- ["@diff.delta"] = { bg = groups.git_change, blend = 20 },
		--
		-- ["@tag"] = { link = "Tag" },
		["@tag.tsx"] = { link = "@constant" },
		["@tag.attribute"] = { link = "@property" },
		["@tag.builtin"] = { link = "@variable.builtin" },
		-- ["@tag.delimiter"] = { fg = palette.subtle },
		--
		-- --- Non-highlighting captures
		-- -- ["@none"] = {},
		-- ["@conceal"] = { link = "Conceal" },
		-- ["@conceal.markdown"] = { fg = palette.subtle },
		--
		-- -- ["@spell"] = {},
		-- -- ["@nospell"] = {},
		--
		-- --- Semantic
		-- ["@lsp.type.comment"] = {},
		-- ["@lsp"] = {},
		-- ["@lsp.type.comment.c"] = { link = "@comment" },
		-- ["@lsp.type.comment.cpp"] = { link = "@comment" },
		-- ["@lsp.type.enum"] = { link = "@type" },
		-- ["@lsp.type.interface"] = { link = "@interface" },
		-- ["@lsp.type.keyword"] = { link = "@keyword" },
		-- ["@lsp.type.namespace"] = { link = "@namespace" },
		-- ["@lsp.type.namespace.python"] = { link = "@variable" },
		-- ["@lsp.type.parameter"] = { link = "@parameter" },
		-- ["@lsp.type.property"] = { link = "@property" },
		-- ["@lsp.type.member"] = { link = "@property" },
		["@lsp.type.variable"] = {}, -- defer to treesitter for regular variables
		-- ["@lsp.type.variable.svelte"] = { link = "@variable" },
		-- ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
		-- ["@lsp.typemod.operator.injected"] = { link = "@operator" },
		-- ["@lsp.typemod.string.injected"] = { link = "@string" },
		-- ["@lsp.typemod.variable.constant"] = { link = "@constant" },
		-- ["@lsp.typemod.variable.defaultLibrary.readonly"] = { link = "@variable.builtin" },
		-- ["@lsp.typemod.variable.readonly"] = { link = "@constant" },
		-- ["@lsp.typemod.variable.injected"] = { link = "@variable" },
	}
end

return M
